#!/bin/bash

set -e
set -x

# clone vmware repository
mkdir -p /usr/local/portage/vmware
wget https://gitweb.gentoo.org/proj/vmware.git/snapshot/master.tar.gz -O- | tar xz -C /usr/local/portage/vmware --strip-components 1

echo 'PORTDIR_OVERLAY="/usr/local/portage/vmware"' >> /etc/portage/make.conf

echo "app-emulation/vmware-workstation ~amd64" > /etc/portage/package.accept_keywords/vmware
echo "app-emulation/vmware-modules ~amd64" >> /etc/portage/package.accept_keywords/vmware
echo "app-emulation/vmware-workstation::vmware" >> /etc/portage/package.unmask
echo "app-emulation/vmware-modules::vmware" >> /etc/portage/package.unmask

# we have to install X, even if we're not going to use it,
# because we can't just install the modules by themselves and there's no headless version

echo "x11-libs/cairo aqua X" > /etc/portage/package.use/vmware
echo "dev-cpp/cairomm aqua X" >> /etc/portage/package.use/vmware
echo "app-emulation/vmware-workstation server bundled-libs vix ovftool" >> /etc/portage/package.use/vmware

emerge app-emulation/vmware-workstation \
       app-emulation/vmware-modules \
       --autounmask-continue

emerge --config vmware-workstation

# required to keep the vagrant plugin happy :rolleyes:
cat <<EOF > /etc/init.d/vmware
#!/bin/bash

/opt/vmware/bin/vmware-networks --status
EOF
chmod +x /etc/init.d/vmware

# hacks to make packer work!
mkdir -p /etc/vmware/vmnet8/dhcpd
cd /etc/vmware/vmnet8
ln -s dhcpd dhcp
ln -s dhcpd.conf dhcp/dhcp.conf

mkdir -p /etc/vmware/vmnet1/dhcpd
cd /etc/vmware/vmnet1
ln -s dhcpd dhcp
ln -s dhcpd.conf dhcp/dhcp.conf

cat <<EOF > /etc/vmware/netmap.conf
# This file is automatically generated.
# Hand-editing this file is not recommended.
network0.name = "Bridged"
network0.device = "vmnet0"
network1.name = "HostOnly"
network1.device = "vmnet1"
network2.name = "NAT"
network2.device = "vmnet8"
EOF

# disabled due to issues when bootstrapping new boxes under vmware.
# enable when ready
# systemctl enable vmware.target

